# Generated by Django 5.2.9 on 2025-12-29 14:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PRINTED', 'Printed'), ('CHECKED_IN', 'Checked-in')], default='PENDING', max_length=20)),
                ('source', models.CharField(choices=[('OYO', 'OYO'), ('AIRBNB', 'Airbnb'), ('WALKIN', 'Page/Walk-in')], default='WALKIN', max_length=10)),
                ('booking_id', models.CharField(blank=True, help_text='Auto-generated if empty', max_length=50)),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('pax', models.IntegerField(default=1)),
                ('nights', models.IntegerField(default=1)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
