# Generated by Django 5.2.9 on 2025-12-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_adminsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestregistration',
            name='security_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, default=1000, max_digits=10, null=True),
        ),
    ]
