# Generated by Django 5.2.9 on 2025-12-30 12:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_guestregistration_security_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('LOGIN', 'Admin Login'), ('VIEW_GUEST', 'Viewed Guest'), ('UPDATE_GUEST', 'Updated Guest'), ('PRINT_PDF', 'Generated PDF')], max_length=20)),
                ('details', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
