# Generated by Django 5.2.9 on 2025-12-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestregistration',
            name='additional_requests',
            field=models.TextField(blank=True, default='[]', help_text='JSON list of requests'),
        ),
        migrations.AddField(
            model_name='guestregistration',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='guestregistration',
            name='room_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
