# Generated by Django 5.2.9 on 2025-12-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_guestregistration_additional_requests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestregistration',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final calculated amount', max_digits=12),
        ),
    ]
