# Generated by Django 5.2.9 on 2025-12-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_guestregistration_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='form_access_code',
            field=models.CharField(blank=True, help_text='Optional code required to view form', max_length=20),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Disable guest form'),
        ),
    ]
