# Generated by Django 5.2.9 on 2025-12-31 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_adminsettings_form_access_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestregistration',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='guestregistration',
            name='mode_of_payment',
            field=models.CharField(choices=[('CASH', 'Cash'), ('GCASH', 'GCash'), ('ONLINE', 'Online/Bank Transfer')], default='CASH', max_length=20),
        ),
    ]
