# Generated by Django 5.2.9 on 2026-01-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_amenity_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestregistration',
            name='mode_of_payment',
            field=models.CharField(choices=[('CASH', 'Cash'), ('GCASH', 'GCash'), ('MAYA', 'Maya'), ('BANK_TRANSFER', 'Bank Transfer')], default='CASH', max_length=20),
        ),
    ]
