# Generated by Django 5.2.9 on 2026-01-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_guestregistration_mode_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='policy_text',
            field=models.TextField(default='Check-in Time: 02:00 PM - 09:00 PM\nCheck-out Time: 12:00 NN\n\n- Early check-in/late check-out subject to availability.\n- Premium Business privilege guests have flexible check-in.\n- Full room rate chargeable for check-in before 07:00 AM.\n- Changes in reservation may require rate changes.\n- Rooms not occupied by 2:00 PM considered no-show.\n- Valid ID required for all guests.\n- Guests under 18 must be accompanied by a parent/guardian.', help_text='Reservation Policy displayed on PDF'),
        ),
    ]
