# Generated by Django 5.2.9 on 2026-01-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_adminsettings_policy_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price_10hr',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='room',
            name='price_22hr',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='room',
            name='price_6hr',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='guestregistration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PRINTED', 'Printed'), ('CHECKED_IN', 'Checked-in'), ('CHECKED_OUT', 'Checked-out')], default='PENDING', max_length=20),
        ),
    ]
