# Generated by Django 5.2.9 on 2026-01-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_room_price_10hr_room_price_22hr_room_price_6hr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='price_22hr',
        ),
    ]
