# Generated by Django 5.2.9 on 2026-01-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_remove_room_price_22hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestregistration',
            name='stay_duration',
            field=models.CharField(blank=True, help_text='Duration label (e.g. 6 Hrs)', max_length=20),
        ),
    ]
