# Generated by Django 5.2.9 on 2026-01-19 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_guestregistration_stay_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='policy_text',
            field=models.TextField(default='Check-in Time: 02:00 PM\nCheck-out Time: 12:00 NN\n\n- Early check-in/late check-out subject to availability.\n- Premium Business privilege guests have flexible check-in.\n- Full room rate chargeable for check-in before 07:00 AM.\n- Changes in reservation may require rate changes.\n- Valid ID required for all guests.\n- Guests under 18 must be accompanied by a parent/guardian.', help_text='Reservation Policy displayed on PDF'),
        ),
        migrations.AlterField(
            model_name='guestregistration',
            name='nights',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
