# Generated by Django 5.2.9 on 2026-01-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_alter_adminsettings_policy_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestregistration',
            name='car_plate',
            field=models.CharField(blank=True, help_text='Optional Car Plate Number', max_length=20, null=True),
        ),
    ]
