# Generated by Django 5.2.9 on 2026-01-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_guestregistration_car_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('DIRTY', 'Dirty/Cleaning'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20),
        ),
    ]
