# Generated by Django 5.2.9 on 2026-01-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_alter_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestregistration',
            name='mode_of_payment',
            field=models.CharField(choices=[('CASH', 'Cash'), ('GCASH', 'GCash'), ('MAYA', 'Maya'), ('BANK_TRANSFER', 'Bank Transfer'), ('PAID_ONLINE', 'Paid Online')], default='CASH', max_length=20),
        ),
    ]
